### ISSUE TITLE
Node 12 actions are deprecated.

### ISSUE THREAD

**Issue by indexOutOfBound5** [Bhacaz/label-regex#4]
This is a pretty cool app and exactly what I needed, if it was working. 

Github gives the following error when trying to run.
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Bhacaz/label-regex@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Wondered if there were any plans to upgrade the Node version this action is running with?

**Comment by Bhacaz** [comment]
Hi, sure I'll look at it, thanks for the issue 😃

**Comment by Bhacaz** [comment]
I created a `v2` release for this change.

**Comment by indexOutOfBound5** [comment]
Awesome, thanks!
