### ISSUE TITLE
Example for nice regex 😅 

### ISSUE THREAD

**Issue by shanike** [Bhacaz/label-regex#7]
Hi! Great action, very minimal. 

At first, I worried it's too minimal for what I was aiming to accomplish,   
but I found that with the magic of regex - it's very much possible!

I'd like to pass on the regex I created, since it might help others!  
(And because I think it's cool)

## The regex example

```regex
^chore\(.*(deps)\)|^(fix|hotfix|feat|refactor|docs)
```

## Examples using the regex:

| PR title                           | -> Label added |
|------------------------------------|-------------|
| chore(deps)                        | deps        |
| chore(dev-deps)                    | deps        |
| fix(admin): updated something      | fix         |
| fix: updated something             | fix         |
| refactor(admin): changed something | refactor    |
| refactor: changed something        | refactor    |
| docs(admin): about something       | docs        |
| docs: about something              | docs        |

## Apologies
I know it's not an issue, but I didn't know where else to submit this example, which I think is worth knowing about, when using the action or when debating about whether to use it.

## Why

I use this regex to mark PRs with labels, which, those lables, will act as headers in the next version's CHANGELOG file

**Comment by Bhacaz** [comment]
Hi, thanks for the feedback. 

Following this I added your example in the README to show how nice thing regex + this action can do 😛.

I hope others will more easily see the potential.
